/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.1-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.campsite.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.campsite.api.model.DateRangeDto;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-01-04T15:28:04.296Z")

@Api(value = "availability")
public interface AvailabilityApi {

	@ApiOperation(value = "Finds Campsite availability", nickname = "getAvailability", notes = "Provides information of the availability of the campsite for a given date range with the default being 1 month.", response = String.class, responseContainer = "List", tags = {
			"reservation", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "Successful operation", response = String.class, responseContainer = "List"),
			@ApiResponse(code = 400, message = "Invalid date range values") })
	@RequestMapping(value = "/availability", produces = { "application/json" }, consumes = {
			"application/json" }, method = RequestMethod.GET)
	ResponseEntity<List<String>> getAvailability(
			@ApiParam(value = "Date range to get availability") @Valid @RequestBody DateRangeDto body);

}
